# Generated by Django 3.2.8 on 2021-12-13 10:32

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='images')),
                ('bio', models.CharField(max_length=30)),
                ('datecreated', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=300)),
                ('shot', cloudinary.models.CloudinaryField(max_length=255, verbose_name='images')),
                ('url', models.URLField()),
                ('datecreated', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='awards.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('text', models.TextField(blank=True, max_length=3000)),
                ('design', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3-Below average'), (4, '4'), (5, '5- Neutral'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10-Excellent')], default=0)),
                ('usability', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3-Below average'), (4, '4'), (5, '5- Neutral'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10-Excellent')], default=0)),
                ('content', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3-Below average'), (4, '4'), (5, '5- Neutral'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10-Excellent')], default=0)),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='awards.projects')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
